create table public.watering_logs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_email text null,
  plot_name text null,
  start_time timestamp with time zone null,
  end_time timestamp with time zone null,
  duration double precision null,
  start_photo_url text null,
  end_photo_url text null,
  issue_reason text null,
  constraint watering_logs_pkey primary key (id)

  -- ADD THIS LINE: This prevents the same plot from having the same start time twice
  constraint unique_watering_session unique (plot_name, start_time)
) TABLESPACE pg_default;
